#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 interface_name ip_address"
    exit 1
fi

interface=$1
ip=$2
gateway=192.168.1.1

ip addr flush dev $interface
ip address add $ip dev $interface
ip route add default via $gateway dev $interface || :
echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 192.168.1.1" > /etc/resolv.conf
ip link set $interface up
echo "Static IP successfully configured for interface $interface"