#!/bin/bash

set -e && cd "${0%/*}"

dir="/run/user/1000/kio-fuse-bETBEZ/smb/root@192.168.1.44/Gentoo/personal/rust_website/files/random"
name="installer.tar.gz"

tar -czf $name ./utility
dest="$dir/$name"

rm "$dest"
mv $name "$dest"