#!/bin/bash
config_location="/tmp/dhcpcd.conf"

doas killall dhcpcd && sleep 0.5

cat <<EOF > $config_location
interface $1
static ip_address=192.168.1.25/24
static routers=192.168.1.1
static domain_name_servers=1.1.1.1 1.0.0.1 192.168.1.1
EOF

echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1\nnameserver 192.168.1.1" | doas tee /etc/resolv.conf

doas ip addr flush $1
doas ip link set dev $1 up
doas dhcpcd -b -f "$config_location" -c "" $1
doas ip route add default via 192.168.1.1 dev $1 || :
doas ip route add default dev $1
