#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ $# -ne 3 ]; then
   echo "Usage: $0 interface ssid password"
   exit 1
fi

interface=$1
ssid=$2
password=$3

rfkill unblock wifi
wpa_passphrase "$ssid" "$password" > /tmp/wpa_supplicant.conf
wpa_supplicant -B -Dwext -i "$interface" -c /tmp/wpa_supplicant.conf
sleep 5
dhclient "$interface"