#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 interface_name ip_address"
    exit 1
fi

interface=$1
ip=$2
gateway=192.168.1.1
dns="1.1.1.1 1.0.0.1 8.8.8.8"

ip address add $ip dev $interface
ip route add default via $gateway dev $interface
echo "nameserver $dns" > /etc/resolv.conf
ip link set $interface up
echo "Static IP successfully configured for interface $interface"