#!/bin/bash

# set up internet first!

PASSWORD="password"

set -e

rmmod pcspkr & echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
pacman --noconfirm -R sudo
pacman --noconfirm -S wget

rm -r /etc/bash
cp -r ./files/* /

wget https://gitea.artixlinux.org/packagesA/artix-mirrorlist/raw/branch/master/trunk/mirrorlist -O /etc/pacman.d/mirrorlist
(sed 's/#//g' <(grep Server <(curl "https://archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4&use_mirror_status=on"))) > /etc/pacman.d/mirrorlist-arch
pacman --noconfirm --disable-download-timeout -Syu artix-archlinux-support zip unzip nano tmux man sshpass git doas tree xonsh openssh openssh-openrc wget docker mlocate docker-compose docker-openrc
pacman-key --populate archlinux
pacman-key --populate artix

echo "permit nopass keepenv :wheel" >> /etc/doas.conf
usermod -a -G wheel root
/root/Scripts/add_user server "$PASSWORD"

chown -R server /home/server
chgrp -R server /home/server

ssh-keygen -f "/home/server/.ssh/id_rsa" -P ""

rc-update add docker
rc-update add sshd
rc-update add startup-service
rc-service docker start
rc-service sshd start
rc-service startup-service start

su - server